# Generated by Django 5.1.3 on 2025-01-25 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Iggy_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Competencias',
            new_name='Diario',
        ),
    ]
