# Generated by Django 5.1.3 on 2025-01-28 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Iggy_App', '0003_clock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clock',
        ),
    ]
