# Generated by Django 5.1.3 on 2025-02-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iggy_App', '0004_delete_clock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matematica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=100)),
                ('nota', models.IntegerField()),
            ],
        ),
    ]
