# Generated by Django 5.1.3 on 2025-02-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iggy_App', '0005_matematica'),
    ]

    operations = [
        migrations.AddField(
            model_name='matematica',
            name='mes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
