# Generated by Django 5.1.3 on 2025-02-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iggy_App', '0006_matematica_mes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matematica',
            name='mes',
        ),
        migrations.AddField(
            model_name='matematica',
            name='answer',
            field=models.CharField(choices=[('A', 'Primer Trimestre'), ('B', 'Segundo Trimestre'), ('C', 'Tercer Trimestre')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
