# Generated by Django 5.1.3 on 2025-02-05 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iggy_App', '0007_remove_matematica_mes_matematica_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lengua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temaL', models.CharField(max_length=100)),
                ('notaL', models.IntegerField()),
                ('answerL', models.CharField(choices=[('A', 'Primer Trimestre'), ('B', 'Segundo Trimestre'), ('C', 'Tercer Trimestre')], max_length=1)),
            ],
        ),
    ]
