# Generated by Django 5.1.3 on 2025-02-05 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iggy_App', '0008_lengua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lengua',
            name='answerL',
            field=models.CharField(choices=[('D', 'Primer Trimestre'), ('E', 'Segundo Trimestre'), ('F', 'Tercer Trimestre')], max_length=1),
        ),
    ]
