# Generated by Django 5.1.3 on 2025-02-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iggy_App', '0009_alter_lengua_answerl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temaI', models.CharField(max_length=100)),
                ('notaI', models.IntegerField()),
                ('answerI', models.CharField(choices=[('G', 'Primer Trimestre'), ('H', 'Segundo Trimestre'), ('I', 'Tercer Trimestre')], max_length=1)),
            ],
        ),
    ]
