# Generated by Django 5.1.3 on 2025-02-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iggy_App', '0011_economia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temaP', models.CharField(max_length=100)),
                ('notaP', models.IntegerField()),
                ('answerP', models.CharField(choices=[('M', 'Primer Trimestre'), ('N', 'Segundo Trimestre'), ('O', 'Tercer Trimestre')], max_length=1)),
            ],
        ),
    ]
