# Generated by Django 5.1.3 on 2025-02-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iggy_App', '0012_programacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra_materias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(choices=[('Ing', 'Ingles'), ('Rdw', 'Reading workshop'), ('Gym', 'Gimnasia'), ('Fsi', 'Fisica'), ('Qim', 'Quimico'), ('Cat', 'Catequesis'), ('Glp', 'Global politics '), ('HstA', 'Historia Argentina '), ('Hsty', 'History'), ('Art', 'Art'), ('Lit', 'Lit')], max_length=5)),
                ('tema', models.CharField(max_length=100)),
                ('nota', models.IntegerField()),
                ('answer', models.CharField(choices=[('M', 'Primer Trimestre'), ('N', 'Segundo Trimestre'), ('O', 'Tercer Trimestre')], max_length=1)),
            ],
        ),
    ]
