# Generated by Django 5.1.3 on 2025-02-08 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Iggy_App', '0014_alter_extra_materias_answer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingles',
        ),
    ]
