# Generated by Django 5.1.3 on 2025-02-08 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Iggy_App', '0015_delete_ingles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extra_materias',
            old_name='answer',
            new_name='answerEx',
        ),
        migrations.RenameField(
            model_name='extra_materias',
            old_name='nota',
            new_name='notaEx',
        ),
        migrations.RenameField(
            model_name='extra_materias',
            old_name='tema',
            new_name='temaEx',
        ),
    ]
